using System.Text.Json;
using System.Text.Json.Serialization;

namespace CodingAgentWebUI.Models;

/// <summary>
/// CI/build metadata baked into the container image at build time.
/// Read from build-info.json (generated by CI, defaults to "local" for dev builds).
/// </summary>
public record BuildInfo
{
    [JsonPropertyName("commitSha")]
    public string CommitSha { get; init; } = "local";

    [JsonPropertyName("branch")]
    public string Branch { get; init; } = "local";

    [JsonPropertyName("buildTimestamp")]
    public string BuildTimestamp { get; init; } = "unknown";

    [JsonPropertyName("runId")]
    public string RunId { get; init; } = "";

    [JsonPropertyName("runNumber")]
    public string RunNumber { get; init; } = "";

    [JsonPropertyName("imageTag")]
    public string ImageTag { get; init; } = "local";

    [JsonPropertyName("repositoryUrl")]
    public string RepositoryUrl { get; init; } = "https://github.com/Chemsorly/coding-agent-automation";

    [JsonIgnore]
    public string ShortSha => CommitSha.Length >= 7 ? CommitSha[..7] : CommitSha;

    [JsonIgnore]
    public bool IsCI => CommitSha != "local";

    [JsonIgnore]
    public string CommitUrl => IsCI && !string.IsNullOrEmpty(RepositoryUrl)
        ? $"{RepositoryUrl.TrimEnd('/')}/commit/{CommitSha}" : "";

    [JsonIgnore]
    public string RunUrl => IsCI && !string.IsNullOrEmpty(RunId) && !string.IsNullOrEmpty(RepositoryUrl)
        ? $"{RepositoryUrl.TrimEnd('/')}/actions/runs/{RunId}"
        : "";

    /// <summary>
    /// Loads build info from build-info.json next to the application binary.
    /// Returns defaults if the file is missing or unreadable.
    /// </summary>
    public static BuildInfo Load()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "build-info.json");
        if (!File.Exists(path))
            return new BuildInfo();

        try
        {
            var json = File.ReadAllText(path);
            return JsonSerializer.Deserialize<BuildInfo>(json) ?? new BuildInfo();
        }
        catch (JsonException)
        {
            return new BuildInfo();
        }
    }
}
