using MessagePack;

namespace CodingAgentWebUI.Pipeline.Models;

/// <summary>
/// Aggregated harness improvement suggestions generated by analyzing accumulated RunFeedback data.
/// Persisted to config/pipeline/harness-suggestions.json.
/// </summary>
[MessagePackObject]
public sealed class HarnessSuggestions
{
    [Key(0)]
    public required int BasedOnRunCount { get; init; }

    [Key(1)]
    public required DateTime GeneratedAtUtc { get; init; }

    [Key(2)]
    public required decimal SuccessRate { get; init; }

    [Key(3)]
    public required IReadOnlyList<HarnessSuggestion> Suggestions { get; init; }
}

/// <summary>
/// A single harness improvement suggestion with rationale and frequency of occurrence.
/// </summary>
[MessagePackObject]
public sealed class HarnessSuggestion
{
    [Key(0)]
    public required int Frequency { get; init; }

    [Key(1)]
    public required string Rationale { get; init; }

    [Key(2)]
    public required string Text { get; init; }
}
