namespace CodingAgentWebUI.Pipeline.Models;

/// <summary>
/// Aggregated harness improvement suggestions generated by analyzing accumulated RunFeedback data.
/// Persisted to config/pipeline/harness-suggestions.json.
/// </summary>
public sealed class HarnessSuggestions
{
    public required DateTime GeneratedAtUtc { get; init; }
    public required int BasedOnRunCount { get; init; }
    public required decimal SuccessRate { get; init; }
    public required IReadOnlyList<HarnessSuggestion> Suggestions { get; init; }
}

/// <summary>
/// A single harness improvement suggestion with rationale and frequency of occurrence.
/// </summary>
public sealed class HarnessSuggestion
{
    public required string Text { get; init; }
    public required string Rationale { get; init; }
    public required int Frequency { get; init; }
}
