using System.Text;

namespace CodingAgentWebUI.Pipeline.Models;

public sealed class IssueAnalysisComment
{
    public required string IssueTitle { get; init; }
    public required string PlannedApproach { get; init; }
    public required IReadOnlyList<string> AffectedComponents { get; init; }
    public required string EstimatedComplexity { get; init; }
    public required string ConfidenceAssessment { get; init; }

    /// <summary>Raw agent analysis output, if available.</summary>
    public string? AgentAnalysis { get; init; }

    /// <summary>Structured assessment from the confidence gate, if available.</summary>
    public AnalysisAssessment? Assessment { get; init; }

    public string ToMarkdown()
    {
        var sb = new StringBuilder();
        sb.AppendLine("## 🤖 Agent Analysis");
        sb.AppendLine();

        // If we have agent-generated analysis, use it as the primary content
        if (!string.IsNullOrWhiteSpace(AgentAnalysis))
        {
            sb.AppendLine(AgentAnalysis);
        }
        else
        {
            sb.AppendLine("### Planned Approach");
            sb.AppendLine(PlannedApproach);
            sb.AppendLine();
            sb.AppendLine("### Affected Components");
            foreach (var component in AffectedComponents)
                sb.AppendLine($"- {component}");
            sb.AppendLine();
            sb.AppendLine("### Estimated Complexity");
            sb.AppendLine(EstimatedComplexity);
            sb.AppendLine();
            sb.AppendLine("### Confidence Assessment");
            sb.AppendLine(ConfidenceAssessment);
        }

        sb.AppendLine();
        sb.AppendLine("---");

        if (Assessment is not null)
        {
            var (emoji, label) = Assessment.Recommendation?.ToLowerInvariant() switch
            {
                "ready" => ("📊", "Ready"),
                "not_ready" => ("⚠️", "Not Ready"),
                "wont_do" => ("🚫", "Won't Do"),
                _ => ("📊", Assessment.Recommendation ?? "Unknown")
            };

            var suffix = Assessment.Recommendation?.ToLowerInvariant() switch
            {
                "not_ready" => " — Issue needs refinement",
                "wont_do" => " — No code changes needed",
                _ => !string.IsNullOrWhiteSpace(Assessment.EstimatedComplexity)
                    ? $" · Complexity: {Assessment.EstimatedComplexity}"
                    : ""
            };

            sb.AppendLine($"{emoji} **Assessment: {label}**{suffix}");

            if (Assessment.Recommendation?.ToLowerInvariant() is "not_ready" or "wont_do"
                && !string.IsNullOrWhiteSpace(Assessment.Reason))
            {
                sb.AppendLine();
                sb.AppendLine($"*Reason: {Assessment.Reason}*");
            }

            if (Assessment.Recommendation?.ToLowerInvariant() == "ready"
                && Assessment.Concerns.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine($"*Concerns: {string.Join("; ", Assessment.Concerns)}*");
            }
        }

        sb.AppendLine();
        var reviewNote = Assessment is null || Assessment.Recommendation?.ToLowerInvariant() == "ready"
            ? "*This analysis was generated by the agent after examining the codebase. Review it before approving implementation.*"
            : "*This analysis was generated by the agent after examining the codebase.*";
        sb.AppendLine(reviewNote);
        return sb.ToString().TrimEnd();
    }

    /// <summary>
    /// Creates an analysis comment from agent-generated analysis output.
    /// The agent's raw output is used as the primary content.
    /// </summary>
    public static IssueAnalysisComment FromAgentAnalysis(IssueDetail issue, string agentOutput, AnalysisAssessment? assessment = null)
    {
        ArgumentNullException.ThrowIfNull(issue);
        ArgumentNullException.ThrowIfNull(agentOutput);

        return new IssueAnalysisComment
        {
            IssueTitle = issue.Title,
            PlannedApproach = string.Empty,
            AffectedComponents = Array.Empty<string>(),
            EstimatedComplexity = string.Empty,
            ConfidenceAssessment = string.Empty,
            AgentAnalysis = agentOutput.Trim(),
            Assessment = assessment
        };
    }
}
