using System.Security.Cryptography;
using System.Text;
using AwesomeAssertions;
using CodingAgentWebUI.Infrastructure.GitHub;
using FsCheck;
using FsCheck.Xunit;
using Microsoft.IdentityModel.JsonWebTokens;
using Moq;
using Octokit;
using ILogger = Serilog.ILogger;
using CodingAgentWebUI.Pipeline;

namespace CodingAgentWebUI.Infrastructure.UnitTests.GitHub;

/// <summary>
/// Tests for GitHubAppAuthService (Requirements 10.1–10.4).
/// Validates private key decoding, JWT generation, and token exchange behavior.
/// </summary>
public class GitHubAppAuthServiceTests
{
    private static readonly Mock<ILogger> MockLogger = new();
    private const string ValidApiUrl = "https://api.github.com";
    private const string ValidClientId = "Iv1.testclient123";
    private const long ValidInstallationId = 12345L;

    /// <summary>
    /// Generates a valid base64-encoded RSA private key PEM for testing.
    /// </summary>
    private static string GenerateValidPrivateKeyBase64()
    {
        using var rsa = RSA.Create(2048);
        var pemString = rsa.ExportRSAPrivateKeyPem();
        var pemBytes = Encoding.UTF8.GetBytes(pemString);
        return Convert.ToBase64String(pemBytes);
    }

    /// <summary>
    /// Creates a mock client factory that returns a mock IGitHubClient with configured GitHubApps.
    /// </summary>
    private static (Func<string, Uri, IGitHubClient> factory, Mock<IGitHubClient> mockClient, Mock<IGitHubAppsClient> mockApps)
        CreateMockClientFactory()
    {
        var mockClient = new Mock<IGitHubClient>();
        var mockApps = new Mock<IGitHubAppsClient>();
        mockClient.Setup(c => c.GitHubApps).Returns(mockApps.Object);

        IGitHubClient Factory(string jwt, Uri uri) => mockClient.Object;

        return (Factory, mockClient, mockApps);
    }

    #region Requirement 10.1: Invalid Private Key Throws GitHubAuthException

    /// <summary>
    /// Requirement 10.1: Construction with invalid base64 string throws GitHubAuthException
    /// with PrivateKeyDecodeFailure kind.
    /// </summary>
    [Fact]
    public void Constructor_InvalidBase64PrivateKey_ThrowsGitHubAuthExceptionWithPrivateKeyDecodeFailure()
    {
        // Arrange
        var invalidBase64 = "not-valid-base64!!!@#$";

        // Act
        var act = () => new GitHubAppAuthService(
            ValidClientId,
            ValidInstallationId,
            invalidBase64,
            ValidApiUrl,
            MockLogger.Object);

        // Assert
        act.Should().Throw<GitHubAuthException>()
            .Which.ErrorKind.Should().Be(GitHubAuthErrorKind.PrivateKeyDecodeFailure);
    }

    /// <summary>
    /// Requirement 10.1: Construction with valid base64 but non-PEM content throws
    /// GitHubAuthException with PrivateKeyDecodeFailure kind.
    /// </summary>
    [Fact]
    public void Constructor_ValidBase64NonPemContent_ThrowsGitHubAuthExceptionWithPrivateKeyDecodeFailure()
    {
        // Arrange — valid base64 encoding of random bytes (not a PEM key)
        var randomBytes = new byte[128];
        Random.Shared.NextBytes(randomBytes);
        var validBase64OfNonPem = Convert.ToBase64String(randomBytes);

        // Act
        var act = () => new GitHubAppAuthService(
            ValidClientId,
            ValidInstallationId,
            validBase64OfNonPem,
            ValidApiUrl,
            MockLogger.Object);

        // Assert
        act.Should().Throw<GitHubAuthException>()
            .Which.ErrorKind.Should().Be(GitHubAuthErrorKind.PrivateKeyDecodeFailure);
    }

    /// <summary>
    /// Requirement 10.1: Construction with empty string throws GitHubAuthException
    /// with PrivateKeyDecodeFailure kind.
    /// </summary>
    [Fact]
    public void Constructor_EmptyPrivateKey_ThrowsGitHubAuthExceptionWithPrivateKeyDecodeFailure()
    {
        // Arrange
        var emptyBase64 = Convert.ToBase64String(Encoding.UTF8.GetBytes(""));

        // Act
        var act = () => new GitHubAppAuthService(
            ValidClientId,
            ValidInstallationId,
            emptyBase64,
            ValidApiUrl,
            MockLogger.Object);

        // Assert
        act.Should().Throw<GitHubAuthException>()
            .Which.ErrorKind.Should().Be(GitHubAuthErrorKind.PrivateKeyDecodeFailure);
    }

    #endregion

    #region Requirement 10.2: JWT Generation Contains Correct App ID as Issuer

    /// <summary>
    /// Requirement 10.2: JWT generated by the service contains the clientId as the issuer claim.
    /// </summary>
    [Fact]
    public void GenerateJwt_ContainsCorrectClientIdAsIssuer()
    {
        // Arrange
        var privateKeyBase64 = GenerateValidPrivateKeyBase64();
        var sut = new GitHubAppAuthService(
            ValidClientId,
            ValidInstallationId,
            privateKeyBase64,
            ValidApiUrl,
            MockLogger.Object);

        // Act
        var jwt = sut.GenerateJwt();

        // Assert
        var handler = new JsonWebTokenHandler();
        var token = handler.ReadJsonWebToken(jwt);
        token.Issuer.Should().Be(ValidClientId);
    }

    /// <summary>
    /// Requirement 10.2: JWT uses RS256 algorithm.
    /// </summary>
    [Fact]
    public void GenerateJwt_UsesRS256Algorithm()
    {
        // Arrange
        var privateKeyBase64 = GenerateValidPrivateKeyBase64();
        var sut = new GitHubAppAuthService(
            ValidClientId,
            ValidInstallationId,
            privateKeyBase64,
            ValidApiUrl,
            MockLogger.Object);

        // Act
        var jwt = sut.GenerateJwt();

        // Assert
        var handler = new JsonWebTokenHandler();
        var token = handler.ReadJsonWebToken(jwt);
        token.Alg.Should().Be("RS256");
    }

    /// <summary>
    /// Requirement 10.2: JWT has three dot-separated parts (header.payload.signature).
    /// </summary>
    [Fact]
    public void GenerateJwt_HasThreeParts()
    {
        // Arrange
        var privateKeyBase64 = GenerateValidPrivateKeyBase64();
        var sut = new GitHubAppAuthService(
            ValidClientId,
            ValidInstallationId,
            privateKeyBase64,
            ValidApiUrl,
            MockLogger.Object);

        // Act
        var jwt = sut.GenerateJwt();

        // Assert
        jwt.Should().NotBeNullOrWhiteSpace();
        jwt.Split('.').Should().HaveCount(3);
    }

    #endregion

    #region Requirement 10.3: GetTokenAsync Failure Throws GitHubAuthException

    /// <summary>
    /// Requirement 10.3: When token exchange fails and no cached token exists,
    /// GetTokenAsync throws GitHubAuthException with TokenExchangeFailure kind.
    /// </summary>
    [Fact]
    public async Task GetTokenAsync_TokenExchangeFails_NoCachedToken_ThrowsGitHubAuthException()
    {
        // Arrange
        var privateKeyBase64 = GenerateValidPrivateKeyBase64();
        var (factory, _, mockApps) = CreateMockClientFactory();

        mockApps
            .Setup(a => a.CreateInstallationToken(It.IsAny<long>()))
            .ThrowsAsync(new ApiException("Simulated API failure", System.Net.HttpStatusCode.InternalServerError));

        var sut = new GitHubAppAuthService(
            ValidClientId,
            ValidInstallationId,
            privateKeyBase64,
            ValidApiUrl,
            MockLogger.Object,
            factory);

        // Act
        var act = () => sut.GetTokenAsync(CancellationToken.None);

        // Assert
        (await act.Should().ThrowAsync<GitHubAuthException>())
            .Which.ErrorKind.Should().Be(GitHubAuthErrorKind.TokenExchangeFailure);
    }

    /// <summary>
    /// Requirement 10.3: When token exchange fails with a network error and no cached token exists,
    /// GetTokenAsync throws GitHubAuthException with TokenExchangeFailure kind.
    /// </summary>
    [Fact]
    public async Task GetTokenAsync_NetworkError_NoCachedToken_ThrowsGitHubAuthException()
    {
        // Arrange
        var privateKeyBase64 = GenerateValidPrivateKeyBase64();
        var (factory, _, mockApps) = CreateMockClientFactory();

        mockApps
            .Setup(a => a.CreateInstallationToken(It.IsAny<long>()))
            .ThrowsAsync(new HttpRequestException("Network unreachable"));

        var sut = new GitHubAppAuthService(
            ValidClientId,
            ValidInstallationId,
            privateKeyBase64,
            ValidApiUrl,
            MockLogger.Object,
            factory);

        // Act
        var act = () => sut.GetTokenAsync(CancellationToken.None);

        // Assert
        (await act.Should().ThrowAsync<GitHubAuthException>())
            .Which.ErrorKind.Should().Be(GitHubAuthErrorKind.TokenExchangeFailure);
    }

    #endregion

    #region Requirement 10.4: GetTokenAsync Returns Token from API Response

    /// <summary>
    /// Requirement 10.4: When token exchange succeeds, GetTokenAsync returns the token
    /// from the GitHub API response.
    /// </summary>
    [Fact]
    public async Task GetTokenAsync_SuccessfulExchange_ReturnsTokenFromApiResponse()
    {
        // Arrange
        var privateKeyBase64 = GenerateValidPrivateKeyBase64();
        var (factory, _, mockApps) = CreateMockClientFactory();

        var expectedToken = "ghs_test_installation_token_abc123";
        var expectedExpiry = DateTimeOffset.UtcNow.AddHours(1);

        var installationToken = new AccessToken(expectedToken, expectedExpiry);

        mockApps
            .Setup(a => a.CreateInstallationToken(ValidInstallationId))
            .ReturnsAsync(installationToken);

        var sut = new GitHubAppAuthService(
            ValidClientId,
            ValidInstallationId,
            privateKeyBase64,
            ValidApiUrl,
            MockLogger.Object,
            factory);

        // Act
        var result = await sut.GetTokenAsync(CancellationToken.None);

        // Assert
        result.Should().Be(expectedToken);
    }

    /// <summary>
    /// Requirement 10.4: The client factory is invoked with the correct API URL.
    /// </summary>
    [Fact]
    public async Task GetTokenAsync_InvokesClientFactoryWithCorrectApiUrl()
    {
        // Arrange
        var privateKeyBase64 = GenerateValidPrivateKeyBase64();
        Uri? capturedUri = null;

        var mockClient = new Mock<IGitHubClient>();
        var mockApps = new Mock<IGitHubAppsClient>();
        mockClient.Setup(c => c.GitHubApps).Returns(mockApps.Object);

        var installationToken = new AccessToken("token", DateTimeOffset.UtcNow.AddHours(1));
        mockApps
            .Setup(a => a.CreateInstallationToken(ValidInstallationId))
            .ReturnsAsync(installationToken);

        Func<string, Uri, IGitHubClient> factory = (jwt, uri) =>
        {
            capturedUri = uri;
            return mockClient.Object;
        };

        var sut = new GitHubAppAuthService(
            ValidClientId,
            ValidInstallationId,
            privateKeyBase64,
            ValidApiUrl,
            MockLogger.Object,
            factory);

        // Act
        await sut.GetTokenAsync(CancellationToken.None);

        // Assert
        capturedUri.Should().NotBeNull();
        capturedUri!.ToString().Should().Be(ValidApiUrl + "/");
    }

    /// <summary>
    /// Requirement 10.4: The client factory is invoked with a non-empty JWT string.
    /// </summary>
    [Fact]
    public async Task GetTokenAsync_InvokesClientFactoryWithNonEmptyJwt()
    {
        // Arrange
        var privateKeyBase64 = GenerateValidPrivateKeyBase64();
        string? capturedJwt = null;

        var mockClient = new Mock<IGitHubClient>();
        var mockApps = new Mock<IGitHubAppsClient>();
        mockClient.Setup(c => c.GitHubApps).Returns(mockApps.Object);

        var installationToken = new AccessToken("token", DateTimeOffset.UtcNow.AddHours(1));
        mockApps
            .Setup(a => a.CreateInstallationToken(ValidInstallationId))
            .ReturnsAsync(installationToken);

        Func<string, Uri, IGitHubClient> factory = (jwt, uri) =>
        {
            capturedJwt = jwt;
            return mockClient.Object;
        };

        var sut = new GitHubAppAuthService(
            ValidClientId,
            ValidInstallationId,
            privateKeyBase64,
            ValidApiUrl,
            MockLogger.Object,
            factory);

        // Act
        await sut.GetTokenAsync(CancellationToken.None);

        // Assert
        capturedJwt.Should().NotBeNullOrWhiteSpace();
        capturedJwt!.Split('.').Should().HaveCount(3);
    }

    #endregion

    #region Property 5: JWT issuer matches clientId

    /// <summary>
    /// Property 5: JWT issuer matches clientId
    /// For any valid clientId string and valid RSA private key, the JWT generated by
    /// GitHubAppAuthService SHALL contain the clientId as the `iss` (issuer) claim.
    /// **Validates: Requirements 10.2**
    /// </summary>
    [Property(MaxTest = 20)]
    public void JwtIssuer_MatchesClientId_ForAnyValidClientId(NonEmptyString clientIdInput)
    {
        // Arrange: Use the generated clientId and a valid RSA key
        var clientId = clientIdInput.Get;

        using var rsa = RSA.Create(2048);
        var pemString = rsa.ExportRSAPrivateKeyPem();
        var pemBytes = Encoding.UTF8.GetBytes(pemString);
        var privateKeyBase64 = Convert.ToBase64String(pemBytes);

        var sut = new GitHubAppAuthService(
            clientId,
            ValidInstallationId,
            privateKeyBase64,
            ValidApiUrl,
            MockLogger.Object);

        // Act: Generate a JWT
        var jwt = sut.GenerateJwt();

        // Assert: The JWT issuer claim matches the clientId exactly
        var handler = new JsonWebTokenHandler();
        var token = handler.ReadJsonWebToken(jwt);
        token.Issuer.Should().Be(clientId);
    }

    #endregion
}
